### ISSUE TITLE
Progress bars are not consistent, cut operation is only copying

### ISSUE THREAD

**Issue by kaii-lb** [kaii-lb/LavenderPhotos#106]
> I noticed another issue that’s happening to me: when moving or copying, the progress bar keeps loading indefinitely during the operation, and the move/cut function only copies files. The progress bar also stays infinite when trimming a video, remaining on "Exporting video", but closing and reopening the app, the trimmed video is generated in a folder called "cache".

 _Originally posted by @victorurizar in [#95](https://github.com/kaii-lb/LavenderPhotos/issues/95#issuecomment-3323246224)_

**Comment by victorurizar** [comment]
Two more things I’ve noticed. When moving files correctly, the file doesn’t retain its original date, so if I move an old image, it gets created as Today. And in albums, the thumbnails don’t reflect the most recent image, it shows a thumbnail that isn’t the most recent one already visible in the album grid. Maybe they have different sorting, as if the grid view respects the modification date while the album thumbnail respects the creation date.

**Comment by kaii-lb** [comment]
> When moving files correctly, the file doesn’t retain its original date, so if I move an old image, it gets created as Today.

theres a toggle for that in settings

second one i'll look into :D

**Comment by victorurizar** [comment]
> theres a toggle for that in settings

Yes, it comes disabled so the date doesn’t change, but it still does. The creation date remains the original, but the modification date is updated to the current one, which makes it show as today. Media classification doesn’t do anything either; even if you set it to date or last modified, it always uses the modification date, not the creation date. This causes the modification date to update to the current date when moved, making it appear as the most recent photo.

**Comment by kaii-lb** [comment]
> As for the video, when cutting and saving a copy, the snackbar bar stays there indefinitely

this has been fixed with [this](https://github.com/kaii-lb/LavenderPhotos/commit/0e3eceaf2ce73df4d803f183b583429393b984f4) commit

> but fails in others. For example, moving an image from Screenshots to Movies

tested out this very config, it works fine, maybe its after the above commit so try that build first?

the log just means that it can't set the "date modified" part of moving for whatever reason

**Comment by victorurizar** [comment]
With the new release, everything is fixed. Only one small thing remains: when moving a really old image, it shows up as 'Today.' The toggle in the settings doesn’t fix it, and I think it’s because moving it changes the 'last modified' date, and the grid displays images based on the modification date. That’s the only thing that doesn’t convince me; everything else is resolved. 

Also, I have a few extra pieces of feedback, but the most important issues are already fixed, thank you!

Extras:

- When there’s a video with a .mpeg extension, the entire gallery gets overloaded.

- It would be nice if, when zooming, the option to allow rotation could be disabled. It’s annoying that the image rotates, and this can even cause videos to bug when zooming, because videos can rotate while zooming.

- The video export process could show a percentage to indicate roughly when it will finish.

- When moving an image, the album where the image currently is shouldn’t appear.

And again. Thank you!

**Comment by kaii-lb** [comment]
interesting cuz rotation locks zoom and zoom locks rotation there, so im not sure how this is happening...
perhaps i can increase the threshold for rotation?

**Comment by victorurizar** [comment]
One more thing, it would be great if the video player’s progress bar were a bit taller vertically or had a larger touch area, since sometimes it’s hard to tap it accurately to move around the video.

By the way, you’re doing an amazing job. Your gallery is the only one that has really convinced me so far. It feels compact, visually appealing, and modern. Thanks!

**Comment by kaii-lb** [comment]
> When moving files correctly, the file doesn’t retain its original date, so if I move an old image, it gets created as Today.

[done](https://github.com/kaii-lb/LavenderPhotos/commit/10c943cf537c3bf9c6950a614d1cb7b842044aa5)

> And in albums, the thumbnails of each album don’t reflect the most recent image, it shows a thumbnail that isn’t the most recent one already visible in the album grid. Maybe they have different sorting, as if the grid view respects the modification date while the album thumbnail respects the creation date.

it [now](https://github.com/kaii-lb/LavenderPhotos/commit/49382e6743a6c9cc6513b930950496e5dac708bd) ignores creation date and only goes for modification date

> It would be nice if, when zooming, the option to allow rotation could be disabled. It’s annoying that the image rotates, and this can even cause videos to bug when zooming, because videos can rotate while zooming.

[added](github.com/kaii-lb/LavenderPhotos/commit/0a78d891f6c4385370c071a99b48eed19fe7b38e)

> The video export process could show a percentage to indicate roughly when it will finish.

[implemented](https://github.com/kaii-lb/LavenderPhotos/commit/0a40bb5c0b94d667e32af63702698944847bdec7)

> One more thing, it would be great if the video player’s progress bar were a bit taller vertically or had a larger touch area, since sometimes it’s hard to tap it accurately to move around the video.

it has been [made taller](https://github.com/kaii-lb/LavenderPhotos/commit/0a78d891f6c4385370c071a99b48eed19fe7b38e)

all of these are testable [here](https://github.com/kaii-lb/LavenderPhotos/actions/runs/18059288217/job/51393280105)

good recommendations, keep them coming :P

**Comment by victorurizar** [comment]
Perfect, this looks great. The only thing that’s still not working is moving old files. When I move an old file, it gets placed under Today, even though I don’t have the option “change date on move” enabled.

Here’s a visual example: this photo was moved and appears under Today, but its actual date isn’t today.

![bugDateOnMove.jpg](https://github.com/user-attachments/assets/85ee984a-f233-47d2-aaf2-167491220a69)

Another thing: while I was trying to move the images, it keeps failing when moving them into certain custom external folders. It doesn’t fail when moving to Camera, Downloads, etc., but it does fail with custom external folders.

Here’s the log:

```
D com.kaii.photos.helpers.MediaPermissions: already have permission for /storage/emulated/0/Test? true
D com.kaii.photos.helpers.MediaPermissions: Finished granting permissions for [/storage/emulated/0/Test]

E com.kaii.photos.mediastore.MediaStoreUtils: Couldn't copy media MediaStoreData(
  type=Image, id=25504,
  uri=content://media/external/images/media/25504,
  mimeType=image/jpeg,
  displayName=IMG_2151.jpg,
  absolutePath=/storage/emulated/0/DCIM/Camera/IMG_2151.jpg,
  bytes=null, size=1682785, width=4000, height=3000
)

W System.err: java.lang.NullPointerException
W System.err:     at com.kaii.photos.mediastore.MediaStoreUtilsKt.getMediaStoreDataFromUri(...)
W System.err:     at com.kaii.photos.helpers.ImageFunctionsKt$moveImageListToPath$1$1.invokeSuspend$lambda$3$lambda$1(...)
W System.err:     at com.kaii.photos.helpers.ImageFunctionsKt$moveImageListToPath$1$1.e(...)
W System.err:     at com.kaii.photos.helpers.b.invoke(...)
W System.err:     at com.kaii.photos.mediastore.MediaStoreUtilsKt$insertMedia$2.invokeSuspend(...)
W System.err:     at com.kaii.photos.mediastore.MediaStoreUtilsKt.insertMedia(...)
W System.err:     at com.kaii.photos.helpers.ImageFunctionsKt$moveImageListToPath$1$1.invokeSuspend(...)
```

**Comment by victorurizar** [comment]
Ok, while I was trying to rename the edited image in the **“Picsart”** album that shows the date bug, it crashed. I tried renaming the image in the **Screenshots** folder and it works, but if I go to a custom external folder, it crashes when renaming.

Yes, I have permissions in that folder, because it lets me edit images normally. It just doesn’t allow renaming.

This is the log:

```
--------- beginning of crash
09-27 23:11:24.448 18023 18119 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-17
09-27 23:11:24.448 18023 18119 E AndroidRuntime: Process: com.kaii.photos, PID: 18023
09-27 23:11:24.448 18023 18119 E AndroidRuntime: android.app.RecoverableSecurityException: com.kaii.photos has no access to content://media/external/images/media/26898
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:197)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:194)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.os.Parcel.readParcelableInternal(Parcel.java:5090)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.os.Parcel.readParcelable(Parcel.java:5072)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3252)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3241)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3224)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:203)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:155)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.content.ContentProviderProxy.update(ContentProviderNative.java:685)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at android.content.ContentResolver.update(ContentResolver.java:2429)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at com.kaii.photos.helpers.ImageFunctionsKt$renameImage$1$1.invokeSuspend(r8-map-id-00949ddaab3115f5ba5e25fd1f65297a3357ab801ca09cdd5abef8344ead5b06:31)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at xf.a.resumeWith(r8-map-id-00949ddaab3115f5ba5e25fd1f65297a3357ab801ca09cdd5abef8344ead5b06:8)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at yg.n0.run(r8-map-id-00949ddaab3115f5ba5e25fd1f65297a3357ab801ca09cdd5abef8344ead5b06:115)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at jc.q.run(r8-map-id-00949ddaab3115f5ba5e25fd1f65297a3357ab801ca09cdd5abef8344ead5b06:214)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at fh.j.run(r8-map-id-00949ddaab3115f5ba5e25fd1f65297a3357ab801ca09cdd5abef8344ead5b06:3)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	at fh.a.run(r8-map-id-00949ddaab3115f5ba5e25fd1f65297a3357ab801ca09cdd5abef8344ead5b06:88)
09-27 23:11:24.448 18023 18119 E AndroidRuntime: 	Suppressed: dh.e: [v1{Cancelling}@2e7fa4a, Dispatchers.IO]
--------- beginning of main
```

**Comment by victorurizar** [comment]
Ok, I noticed that both issues, the one with moving to external folders and permission errors, and the one with renaming in folders with permissions, are not happening in version 1.1.6. They only occur in the most recent nightly build.

> Another thing: while I was trying to move the images, it keeps failing when moving them into certain custom external folders. It doesn’t fail when moving to Camera, Downloads, etc., but it does fail with custom external folders.
> 
> Here’s the log:
> 
> ```
> D com.kaii.photos.helpers.MediaPermissions: already have permission for /storage/emulated/0/Test? true
> D com.kaii.photos.helpers.MediaPermissions: Finished granting permissions for [/storage/emulated/0/Test]
> 
> E com.kaii.photos.mediastore.MediaStoreUtils: Couldn't copy media MediaStoreData(



> Ok, while I was trying to rename the edited image in the **“Picsart”** album that shows the date bug, it crashed. I tried renaming the image in the **Screenshots** folder and it works, but if I go to a custom external folder, it crashes when renaming.
> 
> Yes, I have permissions in that folder, because it lets me edit images normally. It just doesn’t allow renaming.
> 
> This is the log:
> 
> ```
> --------- beginning of crash
> 09-27 23:11:24.448 18023 18119 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-17
> 09-27 23:11:24.448 18023 18119 E AndroidRuntime: Process: com.kaii.photos, PID: 18023

**Comment by victorurizar** [comment]
Listen, the translation is completely wrong. I have it in Spanish, and it says the following: 

'Overwrite Date When Moving
When enabled, the date of the copied/moved media is set to "now", appearing as the most recent.'

I don’t know why it says that. I guess it’s because the translation isn’t in sync with your changes. But it's working nice enabled.

<p align="center">
  <img src="https://github.com/user-attachments/assets/417f5e56-4837-4e5f-8878-e068c6cce576" width="200" />
</p>

**Comment by kaii-lb** [comment]
oh sorry then, the translations are community sourced not by me, so i can't exactly control what changes or not

**Comment by victorurizar** [comment]
Alright, I understand. I hope you can resolve the remaining issues, thanks!

**Comment by kaii-lb** [comment]
check out the latest actions build (which is signed now), both should be fixed

do note that im still trying to figure out how to preserve date with videos, but except for that its working perfectly

**Comment by victorurizar** [comment]
**So the real goal is, when moving or copying, not to update the modification date, but to preserve both the modification and creation dates (the creation date is already kept). The modification date should only be updated when editing the image or video.**

**Comment by kaii-lb** [comment]
please check the latest nightly build, slows down loading a bit, but dates should be 100% on now, and they'll refresh if you view an image

**Comment by victorurizar** [comment]
It works great. It’s already working, but there’s one detail: the albums’ covers are still showing a photo that isn’t the one they should. They don’t display the most recent photo shown in the grid.

<div align="center">
   <img src="https://github.com/user-attachments/assets/742c0af4-e2f2-42fe-8262-c8e778a6126e" width="350">
</div>

The first photo shows the album cover, and the second shows that the cover photo is not the most recent one in the grid. But the moving issue is already fixed, good job, thanks!

**Comment by kaii-lb** [comment]
oh you want the album to show the topmost photo in that album and not which was modified last? why so?
that would make it a lil difficult to track what changed and what not

but yeah glad thats now working :D

**Comment by victorurizar** [comment]
The thing is, the issue with moving photos and the modification date updating is still there. The grid already works perfectly. But the fact that the modification date updates when moving means that if I move an old photo, that photo will show up as the cover instead of the most recent one, it’ll show the one I just moved.

The grid is already working perfectly, but the fact that moving a photo edits the modification date makes the photos I move (no matter if they’re old) show up as the album cover.

**Comment by kaii-lb** [comment]
> And this happens because the action of “Move” shouldn’t be treated as an action to “modify” or “edit” the photo.

that's not something i control, the file is new, the system thinks its modified recently

however mod date and taken date are different. i just thought that showing the most recently modded photo on the cover is sensible since you can see where you moved/copied what.

i'll probably make the cover depend on what the user chose for the sorting in settings

**Comment by victorurizar** [comment]
> i just thought that showing the most recently modded photo on the cover is sensible since you can see where you moved/copied what.

I get your point, but it's very confusing because gallery apps don’t usually work that way. And choosing the sorting for the cover is a good idea and actually a solid solution.

**Comment by victorurizar** [comment]
**It's working perfectly! Thanks. I would close the issue, but I don’t have permissions, so I’ll leave it to you. Thank you very much!**
