### ISSUE TITLE
enhancement in editing tools

### ISSUE THREAD

**Issue by singh9596** [kaii-lb/LavenderPhotos#51]
Love the app! I was looking for an alternative to Simple Gallery Pro, but I’ve noticed that other gallery apps don’t offer convenient text editing. Once you add text, you can’t easily manipulate it. any changes you make only apply to new text.

Suggestions:
.Allow pinch-to-zoom on text to adjust its size.
.Make it possible to change the color of existing text.
.Improve the overall text editing experience.
.Moreover the gallery is showing me only the images in camera folder.

**Comment by kaii-lb** [comment]
thanks for the kind words!

1. pinch to zoom is already a thing, tho it needs improving

2. yes that would be a good idea, i'll try to do it

3. could you give some recommendations?

4. Lavender Photos only adds albums when you want it to (from the plus icon on the top right). If howeever you want all the folders on your device, go into settings -> general -> auto detect albums. that'll add everything (tho it takes a sec to find everything and it'll show u a progress notification)

**Comment by singh9596** [comment]
![Image](https://github.com/user-attachments/assets/5d9a40fe-059e-4f3a-a085-6cbeec1b0e5e)

The setting is enabled by default. It shows all the images in the search section but doesn't display them in the album. 
. For recommendations, I use Simple Gallery Pro or PicsArt to edit text on images.
. I’ve tried pinch-zooming the text, but it doesn’t do anything.
. I forgot to mention, why does it rotate the image when entering edit mode?

**Comment by kaii-lb** [comment]
> The setting is enabled by default. It shows all the images in the search section but doesn't display them in the album.

oh well i good fix that, disable and enable it for the time being

**Comment by singh9596** [comment]
https://drive.google.com/drive/folders/1HeQmFg-QYEnClVLIk21P2E6yRZX4hJ6o

**Comment by kaii-lb** [comment]
oh! i see the issue, yeah should be a simple fix, i currently am working on something life related so i can't work on lavender photos, i'll fix that as soon as i can tho :D

as for video editing, that's gonna take a lot more effort lol, its coming tho for sure

**Comment by singh9596** [comment]
Thanks for taking the note. Take your time

**Comment by kaii-lb** [comment]
fixed! closing after someone tests that its good enough

**Comment by singh9596** [comment]
Great. I'll be waiting for the release

**Comment by singh9596** [comment]
Editing is still not convenient. I'm attaching the drive link with the screen recordings and a screenshot of media folder not loading other than camera. Moreover I guess only the certain type of image dimension opens the image in landscape mode while editing. https://drive.google.com/drive/folders/1JHX6EVKTRv-5IY2ZOSin26Me1TmOXzQh

**Comment by kaii-lb** [comment]
i'll try to improve it further

**Comment by singh9596** [comment]
> > Editing is still not convenient. I'm attaching the drive link with the screen recordings and a screenshot of media folder not loading other than camera. Moreover I guess only the certain type of image dimension opens the image in landscape mode while editing. https://drive.google.com/drive/folders/1JHX6EVKTRv-5IY2ZOSin26Me1TmOXzQh
> 
> hey seems like the link is dead, do you mind reuploading so i can fix the issue?

https://drive.google.com/drive/folders/1NRYPjP-9TER4aeOngEpUVoz43sQghroZ
Here's the updated one

**Comment by kaii-lb** [comment]
the blur thingy and auto detect albums have been fixed, just not released yet

as for the infinite loading i need a log for that
and the zooming in i'll try fixing it soon 

thank you!

**Comment by kaii-lb** [comment]
release up, can you test please?

**Comment by singh9596** [comment]
> release up, can you test please?

Infinite loading gone, album detection is working right. Editing is pretty much fixed with little more enhancement needed. I've uploaded the screenrecording in the same drive link. Thankyou

**Comment by kaii-lb** [comment]
> > release up, can you test please?
> 
> Infinite loading gone, album detection is working right. Editing is pretty much fixed with little more enhancement needed. I've uploaded the screenrecording in the same drive link. Thankyou 

nice! glad to know those are working. editing should still be a lil more responsive and i need to add a "hiide controls" button,  possibly rework the ui.
